//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoodaQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoodaQuery.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.CodeDom.MemberAttributes contextMenuDatabases_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("contextMenuDatabases.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Drawing.Point contextMenuDatabases_Location {
            get {
                object obj = ResourceManager.GetObject("contextMenuDatabases.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes contextMenuDatabases_Modifiers {
            get {
                object obj = ResourceManager.GetObject("contextMenuDatabases.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes contextMenuItemCopy_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("contextMenuItemCopy.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes contextMenuItemCopy_Modifiers {
            get {
                object obj = ResourceManager.GetObject("contextMenuItemCopy.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes contextMenuItemSelectAll_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("contextMenuItemSelectAll.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes contextMenuItemSelectAll_Modifiers {
            get {
                object obj = ResourceManager.GetObject("contextMenuItemSelectAll.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes csvResults_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("csvResults.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Text.UTF8Encoding csvResults_Encoding {
            get {
                object obj = ResourceManager.GetObject("csvResults.Encoding", resourceCulture);
                return ((System.Text.UTF8Encoding)(obj));
            }
        }
        
        internal static bool csvResults_Locked {
            get {
                object obj = ResourceManager.GetObject("csvResults.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes csvResults_Modifiers {
            get {
                object obj = ResourceManager.GetObject("csvResults.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes imageList1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("imageList1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Windows.Forms.ImageListStreamer imageList1_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageList1.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        internal static System.Drawing.Point imageList1_Location {
            get {
                object obj = ResourceManager.GetObject("imageList1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes imageList1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("imageList1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes mainMenu1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("mainMenu1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Drawing.Point mainMenu1_Location {
            get {
                object obj = ResourceManager.GetObject("mainMenu1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes mainMenu1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("mainMenu1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem2_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem2.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem3_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem3.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem4_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem4.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem5_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem5.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem5_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem5.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem6_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem6.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem6_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem6.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem7_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem7.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem7_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem7.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem8_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem8.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem8_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem8.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem9_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem9.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItem9_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem9.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileExit_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileExit.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileExit_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileExit.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileNew_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileNew.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileNew_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileNew.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileOpen_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileOpen.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileOpen_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileOpen.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileSave_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileSave.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileSave_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileSave.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileSaveAs_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileSaveAs.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemFileSaveAs_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemFileSaveAs.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectNew_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectNew.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectNew_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectNew.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectOpen_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectOpen.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectOpen_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectOpen.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectProperties_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectProperties.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectProperties_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectProperties.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectSave_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectSave.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuItemProjectSave_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItemProjectSave.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemQueryRun_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemQueryRun.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes menuitemQueryRun_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuitemQueryRun.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes messagesTextBox_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("messagesTextBox.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool messagesTextBox_Locked {
            get {
                object obj = ResourceManager.GetObject("messagesTextBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes messagesTextBox_Modifiers {
            get {
                object obj = ResourceManager.GetObject("messagesTextBox.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("panel1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel1_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("panel1.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size panel1_GridSize {
            get {
                object obj = ResourceManager.GetObject("panel1.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool panel1_Locked {
            get {
                object obj = ResourceManager.GetObject("panel1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("panel1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel1_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("panel1.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel2_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("panel2.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel2_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("panel2.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size panel2_GridSize {
            get {
                object obj = ResourceManager.GetObject("panel2.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool panel2_Locked {
            get {
                object obj = ResourceManager.GetObject("panel2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("panel2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel2_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("panel2.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel3_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("panel3.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel3_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("panel3.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size panel3_GridSize {
            get {
                object obj = ResourceManager.GetObject("panel3.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool panel3_Locked {
            get {
                object obj = ResourceManager.GetObject("panel3.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("panel3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel3_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("panel3.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel4_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("panel4.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel4_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("panel4.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size panel4_GridSize {
            get {
                object obj = ResourceManager.GetObject("panel4.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool panel4_Locked {
            get {
                object obj = ResourceManager.GetObject("panel4.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("panel4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel4_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("panel4.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel5_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("panel5.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel5_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("panel5.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size panel5_GridSize {
            get {
                object obj = ResourceManager.GetObject("panel5.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool panel5_Locked {
            get {
                object obj = ResourceManager.GetObject("panel5.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes panel5_Modifiers {
            get {
                object obj = ResourceManager.GetObject("panel5.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool panel5_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("panel5.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes recordsetContextMenu_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("recordsetContextMenu.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Drawing.Point recordsetContextMenu_Location {
            get {
                object obj = ResourceManager.GetObject("recordsetContextMenu.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes recordsetContextMenu_Modifiers {
            get {
                object obj = ResourceManager.GetObject("recordsetContextMenu.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes resultSet_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("resultSet.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool resultSet_Locked {
            get {
                object obj = ResourceManager.GetObject("resultSet.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes resultSet_Modifiers {
            get {
                object obj = ResourceManager.GetObject("resultSet.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes soqlPrettyPrint_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("soqlPrettyPrint.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Text.UTF8Encoding soqlPrettyPrint_Encoding {
            get {
                object obj = ResourceManager.GetObject("soqlPrettyPrint.Encoding", resourceCulture);
                return ((System.Text.UTF8Encoding)(obj));
            }
        }
        
        internal static bool soqlPrettyPrint_Locked {
            get {
                object obj = ResourceManager.GetObject("soqlPrettyPrint.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes soqlPrettyPrint_Modifiers {
            get {
                object obj = ResourceManager.GetObject("soqlPrettyPrint.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes splitter2_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("splitter2.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool splitter2_Locked {
            get {
                object obj = ResourceManager.GetObject("splitter2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes splitter2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("splitter2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes statusBar1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("statusBar1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool statusBar1_Locked {
            get {
                object obj = ResourceManager.GetObject("statusBar1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes statusBar1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBar1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabControl1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabControl1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabControl1_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabControl1.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabControl1_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabControl1.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabControl1_Locked {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabControl1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabControl1_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabControl1.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageCsv_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageCsv.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageCsv_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageCsv.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabPageCsv_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabPageCsv.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabPageCsv_Locked {
            get {
                object obj = ResourceManager.GetObject("tabPageCsv.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageCsv_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageCsv.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageCsv_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageCsv.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageMessages_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageMessages.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageMessages_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageMessages.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabPageMessages_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabPageMessages.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabPageMessages_Locked {
            get {
                object obj = ResourceManager.GetObject("tabPageMessages.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageMessages_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageMessages.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageMessages_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageMessages.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPagePrettyPrint_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabPagePrettyPrint.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPagePrettyPrint_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabPagePrettyPrint.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabPagePrettyPrint_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabPagePrettyPrint.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabPagePrettyPrint_Locked {
            get {
                object obj = ResourceManager.GetObject("tabPagePrettyPrint.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPagePrettyPrint_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabPagePrettyPrint.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPagePrettyPrint_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabPagePrettyPrint.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageRecordSet_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageRecordSet.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageRecordSet_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageRecordSet.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabPageRecordSet_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabPageRecordSet.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabPageRecordSet_Locked {
            get {
                object obj = ResourceManager.GetObject("tabPageRecordSet.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageRecordSet_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageRecordSet.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageRecordSet_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageRecordSet.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageTSql_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageTSql.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageTSql_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageTSql.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabPageTSql_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabPageTSql.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabPageTSql_Locked {
            get {
                object obj = ResourceManager.GetObject("tabPageTSql.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageTSql_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageTSql.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageTSql_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageTSql.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageXml_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageXml.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageXml_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageXml.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size tabPageXml_GridSize {
            get {
                object obj = ResourceManager.GetObject("tabPageXml.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool tabPageXml_Locked {
            get {
                object obj = ResourceManager.GetObject("tabPageXml.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes tabPageXml_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tabPageXml.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool tabPageXml_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("tabPageXml.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes TextEditorControl1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("TextEditorControl1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Text.UTF8Encoding TextEditorControl1_Encoding {
            get {
                object obj = ResourceManager.GetObject("TextEditorControl1.Encoding", resourceCulture);
                return ((System.Text.UTF8Encoding)(obj));
            }
        }
        
        internal static bool TextEditorControl1_Locked {
            get {
                object obj = ResourceManager.GetObject("TextEditorControl1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes TextEditorControl1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("TextEditorControl1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBar1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBar1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static bool toolBar1_Locked {
            get {
                object obj = ResourceManager.GetObject("toolBar1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBar1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBar1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButton1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButton1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonConnection_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonConnection.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonConnection_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonConnection.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonNew_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonNew.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonNew_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonNew.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonOpen_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonOpen.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonOpen_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonOpen.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonRun_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonRun.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonRun_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonRun.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonSave_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonSave.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarButtonSave_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButtonSave.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarSeparator1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarSeparator1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes toolBarSeparator1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarSeparator1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes translatedSql_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("translatedSql.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Text.UTF8Encoding translatedSql_Encoding {
            get {
                object obj = ResourceManager.GetObject("translatedSql.Encoding", resourceCulture);
                return ((System.Text.UTF8Encoding)(obj));
            }
        }
        
        internal static bool translatedSql_Locked {
            get {
                object obj = ResourceManager.GetObject("translatedSql.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes translatedSql_Modifiers {
            get {
                object obj = ResourceManager.GetObject("translatedSql.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes xmlResults_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("xmlResults.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        internal static System.Text.UTF8Encoding xmlResults_Encoding {
            get {
                object obj = ResourceManager.GetObject("xmlResults.Encoding", resourceCulture);
                return ((System.Text.UTF8Encoding)(obj));
            }
        }
        
        internal static bool xmlResults_Locked {
            get {
                object obj = ResourceManager.GetObject("xmlResults.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.CodeDom.MemberAttributes xmlResults_Modifiers {
            get {
                object obj = ResourceManager.GetObject("xmlResults.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
